name: tokoku-react
run-name: version
on:
  push:
    tags:
    - v*
jobs: 
  Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Login to docker
        run: echo -n ${{secrets.GITHUB_TOKEN}} | docker login ghcr.io --username ${{github.actor}} --password-stdin
      - name: build images
        run: docker build . -t ghcr.io/${{github.repository}}:latest
      - name: Push to ghcr.io
        run: docker push ghcr.io/${{github.repository}}:latest

  
